### ISSUE TITLE
This example unfortunately no longer works

### ISSUE THREAD

**Issue by Jamzy01** [sotanakamura/winui-rust#1] opened 2023-11-16 20:53 UTC
Not sure if you know this but your crate no longer works, likely due to windows-app-rs being discontinued and therefore unmaintained. Additionally windows-app-rs has been since yanked from crates.io, making it an unviable solution unless you want to clone the GitHub repo to your local machine. Your example looked amazing, and I'm just sad it doesn't work anymore, any chance you'd think about rewriting your example with another library, is it even possible? Honestly I'd be happy to try if you just point me in the right direction.

**Comment by sotanakamura** [comment] 2023-11-16 23:30
Fixing the problem is so hard because it is related to the internals of WinUI that only WinUI developers know. WinUI will become an open-source project soon. The maintainer of the crate may restart maintaining it. By the way, the crate was archived when I created this sample, so it may still work. If I have time, I will check the code. Thank you.

**Comment by sotanakamura** [comment] 2023-11-17 01:00
I have confirmed that it still works in my environment. You may be missing a component.

**Comment by Jamzy01** [comment] 2023-11-17 02:55
Yeah I get this error message when I try to launch the exe from code lldb (and the same if I just run the exe from file explorer in the target directory): 

![image](https://github.com/sotanakamura/winui-rust/assets/103490514/5ecf4791-d4c1-438d-aa9b-65838bf38f61)

```
winui.exe - This application could not be started
This application requires the Windows App Runtime
    Version 1.1
    (MSIX package version >= 1001.524.1918.0)
```

All Win UI 3 apps work for, but I should probably point out that I am on Windows 10.
I have tried installing a new winrt it like the error message says, but I haven't had like any experience with winui in xaml, so I don't really know how to install things like the windows app runtime.

If it helps, this is my windows version
![image](https://github.com/sotanakamura/winui-rust/assets/103490514/e07ad646-f79f-4e1a-b7fa-8345a8ebe97e)

**Comment by sotanakamura** [comment] 2023-11-17 03:00
It is good information! You can click "yes" in the message box and you will find [the windows app runtime installer v1.1.0](https://aka.ms/windowsappsdk/1.1/1.1.0/windowsappruntimeinstall-1.1.0-x64.exe) in [Older downloads for the Windows App SDK](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/older-downloads)

**Comment by Jamzy01** [comment] 2023-11-17 03:31
Yeah, I know, I tried it yesterday and I just tried it again. I even restarted my laptop after installing it because I thought some changes may not be being applied, but I still get the exact same error message. What is your version of windows btw?

**Comment by sotanakamura** [comment] 2023-11-17 03:41
Windows 11 Home
22H2
22621.2428

Can you run the following command and find the windows app runtime? Is the version greater than 1001.524.1918.0?
`winget list --name WinAppRuntime.Main.1.1`

**Comment by Jamzy01** [comment] 2023-11-17 03:57
![image](https://github.com/sotanakamura/winui-rust/assets/103490514/2c9ec90b-2627-443c-91b2-29d3b61421d6)
So yeah, it is

**Comment by sotanakamura** [comment] 2023-11-17 04:08
Then, I have no idea.

**Comment by Jamzy01** [comment] 2023-11-17 04:11
But what kind of things have you installed, at the moment I haven't installed Microsoft visual studio or the windows sdk because I've never needed it. I mean it would be weird to be a requirement considering that 90% of consumers that I send the exe to won't have windows sdk or visual studio, but honestly, I have no idea what I'm missing.

**Comment by sotanakamura** [comment] 2023-11-17 04:40
I think only the windows app runtime is required. It is indicated by the error message or it is installed by MSIX dependencies mechanism. The problem is that the app doesn't recognize the windows app runtime. You may need to run the app as an administrator or do something because your OS is windows 10 Education, right?

**Comment by Jamzy01** [comment] 2023-11-17 04:41
Yeah I've already tried running it as an administrator, doesn't work

**Comment by Jamzy01** [comment] 2023-11-17 04:42
Actually you might be right, yeah I'm on education, I can try later with another laptop which is on windows 11, still seems weird that it wouldn't work bc again other win UI 3 apps work fine

**Comment by sotanakamura** [comment] 2023-11-17 04:50
So my environment is special, but I don't know what is special. I will find the cause.

**Comment by Jamzy01** [comment] 2023-11-17 06:01
Not sure if this helps you, but on my Windows 11 machine I get this error when I run it using code lldb (btw it just crashes when running the exe from file explorer, even when run as an administrator)

![image](https://github.com/sotanakamura/winui-rust/assets/103490514/c69b98b7-19d4-44ee-af06-a2c614feec5f)

Windows version:

![image](https://github.com/sotanakamura/winui-rust/assets/103490514/1027bbfa-6c13-404a-9c31-c80cb32c264e)

**Comment by sotanakamura** [comment] 2023-11-21 08:57
Installing Windows App SDK and Windows App Runtime fixes this problem. Please install those components using the following command;

```
winget install "Visual Studio Community 2022"  --override "--add Microsoft.VisualStudio.Workload.NativeDesktop  Microsoft.VisualStudio.ComponentGroup.WindowsAppSDK.Cpp"  -s msstore
```

**Comment by Jamzy01** [comment] 2023-11-21 09:25
```
PS C:\Users\...\Documents\Programming\winui-rust> winget install "Visual Studio Community 2022"  --override "--add Microsoft.VisualStudio.Workload.NativeDesktop  Microsoft.VisualStudio.ComponentGroup.WindowsAppSDK.Cpp"  -s msstore
Found an existing package already installed. Trying to upgrade the installed package...
No available upgrade found.
No newer package versions are available from the configured sources.
```

Both my windows 10 and 11 machines say that the packages are already installed (they literally outputted the exact same thing in terminal).

I just checked my visual studio installation on windows 11 and confirmed that the Windows 10 SDK (10.0.19041.0) is actually installed.

As much as I want this to work, I'm starting to think it's not really worth pursuing. Making Win UI 3 apps in rust would be incredible, but even if I get a basic app to work, I assume countless other things will break easily or just not work whatsoever (especially considering that your demo uses a now unmaintained crate). As you said before, soon Win UI 3 will become open source, and then maybe this will become worth revisiting, but until then I'm thinking it's just not worth it. Microsoft and their undocumented closed source software ):

Unless you have any last ditch ideas, you can just close this issue if you want

**Comment by sotanakamura** [comment] 2023-11-21 10:03
Please install "Desktop development with C++" workload and "Windows App SDK C++ Templates" (at the bottom of the Installation details pane) using Visual Studio Installer. I tried it in a clean Windows 11 sandbox, and I confirmed that it works. It should work, so I will close this issue. As you said, it is not ready to use. When it gets ready, please come back again.

**Closed as completed by sotanakamura** 2023-11-21 10:03 UTC
